//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhitSchool.components
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public int id { get; set; }
        public string title { get; set; }
        public string capital { get; set; }
        public Nullable<int> squareContry { get; set; }
        public Nullable<int> populationContry { get; set; }
        public string continent { get; set; }
    }
}
