//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhitSchool.components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int TabNumber { get; set; }
        public string Code { get; set; }
        public string LastName { get; set; }
        public string Position { get; set; }
        public string Salary { get; set; }
        public Nullable<int> Boss { get; set; }
    }
}
