//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhitSchool.components
{
    using System;
    using System.Collections.Generic;
    
    public partial class learner
    {
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Specialization { get; set; }
        public string School { get; set; }
        public Nullable<double> Scores { get; set; }
    }
}
